Repository denkylabs/denkybot, pull requests merged in 2022-07, with the labels that each got.

#30 [WIP] feat: add /suggest & /config suggestions
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package.json
  src/bot/commands/Configuration/_config_suggestions.ts
  src/bot/commands/Configuration/config.ts
  src/bot/commands/Configuration/data/config.ts
  src/bot/commands/Information/_server_banner.ts
  src/bot/commands/Information/_server_icon.ts
  src/bot/commands/Information/_server_info.ts
  src/bot/commands/Information/_user_avatar.ts
  src/bot/commands/Information/_user_banner.ts
  src/bot/commands/Information/_user_info.ts
  src/bot/commands/Information/data/server.ts
  src/bot/commands/Information/data/user.ts
  src/bot/commands/Information/server.ts
  src/bot/commands/Information/user.ts
  src/bot/commands/Moderation/data/poll.ts
  src/bot/commands/Moderation/poll.ts
  src/bot/commands/Text/_text_claps.ts
  src/bot/commands/Text/_text_emojify.ts
  src/bot/commands/Text/_text_invert.ts
  src/bot/commands/Text/_text_vaporwave.ts
  src/bot/commands/Text/data/text.ts
  src/bot/commands/Text/text.ts
  src/bot/commands/Utils/afk.ts
  src/bot/commands/Utils/data/afk.ts
  src/bot/commands/Utils/data/help.ts
  src/bot/commands/Utils/data/ping.ts
  src/bot/commands/Utils/data/suggestion.ts
  src/bot/commands/Utils/help.ts
  src/bot/commands/Utils/ping.ts
  src/bot/commands/Utils/suggestion.ts
  src/bot/events/guildCreate.ts
  src/bot/events/guildDelete.ts
  src/bot/events/interactionCreate.ts
  src/bot/events/messageCreate.ts
  src/bot/index.ts
  src/bot/utils/Poster.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandCategories/en_US/index.ts
  src/locales/commandCategories/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
  src/locales/permissions/en_US/index.ts
  src/locales/permissions/pt_BR/index.ts
  src/sharding/shard.ts
  src/structures/Command.ts
Labels: enhancement

#37 feat: webserver interactions
  config.example.json
  package.json
  src/bot/utils/Initializer.ts
  src/bot/webserver/server.ts
Labels: enhancement

#38 feat: logger
  src/bot/events/ready.ts
  src/bot/managers/LanguageManager.ts
  src/bot/tasks/auto-post-stats.ts
  src/bot/utils/Initializer.ts
  src/bot/utils/Logger.ts
  src/bot/utils/Poster.ts
  src/bot/webserver/server.ts
  src/sharding/shard.ts
  src/types/Client.ts
Labels: enhancement

#39 initializer: show amount of items that were loaded
  src/bot/events/ready.ts
  src/bot/managers/LanguageManager.ts
  src/bot/utils/Initializer.ts
Labels: enhancement

#40 refactor: use undici instead of axios
  package.json
  src/bot/utils/Poster.ts
Labels: enhancement

#41 feat: add bot invite command
  src/bot/commands/Information/_bot_invite.ts
  src/bot/commands/Information/bot.ts
  src/bot/commands/Information/data/bot.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
Labels: enhancement

#42 suggestions: fixes & add localization
  src/bot/commands/Utils/data/suggestion.ts
  src/bot/commands/Utils/suggestion.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
Labels: enhancement

#48 refactor: database
  .env.example
  .github/workflows/typescript.yml
  package.json
  src/bot/commands/Configuration/_config_suggestions.ts
  src/bot/commands/Utils/afk.ts
  src/bot/commands/Utils/ping.ts
  src/bot/commands/Utils/suggestion.ts
  src/bot/events/messageCreate.ts
  src/bot/managers/DatabaseManager.ts
  src/bot/modules/Database.ts
  src/prisma/schema.prisma
  src/types/Client.ts
Labels: meta: feature, meta: bug fix, meta: refactor, status: WIP, priority: high

#53 fix(deps): bump discord.js to latest dev version
  package.json
  src/bot/commands/Configuration/_config_suggestions.ts
  src/bot/commands/Utils/help.ts
  src/bot/commands/Utils/suggestion.ts
Labels: meta: dependencies, meta: refactor, priority: medium

#54 fix: localize cooldown messages
  src/bot/commands/Configuration/_config_suggestions.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
Labels: meta: refactor, priority: high, type: localization

#56 feat: add labeler action
  .github/labeler.yml
  .github/workflows/auto-label.yml
  .github/workflows/eslint-check.yml
  .gitignore
  yarn.lock
Labels: meta: feature, priority: low, type: github

#47 feat: ban command
  src/bot/commands/Moderation/ban.ts
  src/bot/commands/Moderation/data/ban.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
Labels: meta: feature, priority: medium, type: localization

#57 refactor: remove `guildOnly` property
  src/bot/commands/Configuration/_config_suggestions.ts
  src/bot/commands/Configuration/config.ts
  src/bot/commands/Information/_bot_invite.ts
  src/bot/commands/Information/_bot_vote.ts
  src/bot/commands/Information/_server_banner.ts
  src/bot/commands/Information/_server_icon.ts
  src/bot/commands/Information/_server_info.ts
  src/bot/commands/Information/_user_avatar.ts
  src/bot/commands/Information/_user_banner.ts
  src/bot/commands/Information/_user_info.ts
  src/bot/commands/Information/bot.ts
  src/bot/commands/Information/data/bot.ts
  src/bot/commands/Information/server.ts
  src/bot/commands/Information/user.ts
  src/bot/commands/Moderation/poll.ts
  src/bot/commands/Text/_text_claps.ts
  src/bot/commands/Text/_text_emojify.ts
  src/bot/commands/Text/_text_invert.ts
  src/bot/commands/Text/_text_vaporwave.ts
  src/bot/commands/Text/text.ts
  src/bot/commands/Utils/afk.ts
  src/bot/commands/Utils/help.ts
  src/bot/commands/Utils/ping.ts
  src/bot/commands/Utils/suggestion.ts
  src/bot/events/interactionCreate.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/structures/Command.ts
Labels: meta: refactor, meta: cleanup, priority: low, type: consistency, type: localization, type: events, type: interactions

#59 feat(help): notify user about guild-only commands
  .eslintrc.json
  src/bot/commands/Configuration/_config_suggestions.ts
  src/bot/commands/Information/_user_avatar.ts
  src/bot/commands/Moderation/poll.ts
  src/bot/commands/Utils/help.ts
  src/bot/commands/Utils/suggestion.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
Labels: meta: feature, status: accepted, meta: cleanup, type: localization

#65 feat: Sentry and Webhook
  .env.example
  config.example.json
  package.json
  src/bot/utils/Initializer.ts
  src/bot/utils/logger/Sentry.ts
  src/bot/utils/logger/Webhook.ts
  src/sharding/shard.ts
  yarn.lock
Labels: meta: feature, status: accepted

#69 feat: wikipedia command
  src/bot/commands/Utils/data/wikipedia.ts
  src/bot/commands/Utils/wikipedia.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
Labels: meta: feature, status: WIP, priority: low

#76 chore: use typescript stable
  package.json
  yarn.lock
Labels: meta: dependencies

#77 feat: implement redis caching
  .env.example
  .github/workflows/eslint-check.yml
  .github/workflows/typescript.yml
  config.example.json
  package.json
  src/bot/managers/DatabaseManager.ts
  src/bot/modules/Database.ts
  yarn.lock
Labels: meta: feature, priority: medium, type: database

#81 fix(suggestions): add missing locales
  src/locales/command/en_US/index.ts
Labels: meta: bug fix, priority: medium

#71 feat: add mute command
  package.json
  src/bot/commands/Moderation/ban.ts
  src/bot/commands/Moderation/data/mute.ts
  src/bot/commands/Moderation/mute.ts
  src/locales/command/en_US/index.ts
  src/locales/command/pt_BR/index.ts
  src/locales/commandDescriptions/en_US/index.ts
  src/locales/commandDescriptions/pt_BR/index.ts
  src/locales/commandNames/en_US/index.ts
  src/locales/commandNames/pt_BR/index.ts
  yarn.lock
Labels: meta: feature, priority: low

#98 feat: kick command
  packages/bot/package.json
  packages/bot/src/commands/Moderation/data/kick.ts
  packages/bot/src/commands/Moderation/kick.ts
  packages/bot/src/lib/utils/Initializer.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/locales/assets/commandDescriptions/en_US/index.ts
  packages/locales/assets/commandDescriptions/pt_BR/index.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
Labels: meta: feature, priority: low, package: bot, package: locales

#83 feat: notify member when accepting/denying suggestions
  .gitignore
  packages/bot/src/commands/Configuration/_config_suggestions.ts
  packages/bot/src/commands/Utils/suggestion.ts
  packages/bot/src/lib/managers/DatabaseManager.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/prisma/schemas/cockroachdb.prisma
  packages/prisma/schemas/migrations/20220713032042_notices/migration.sql
  packages/prisma/schemas/migrations/migration_lock.toml
  packages/prisma/schemas/mongodb.prisma
  packages/prisma/schemas/postgres.prisma
Labels: meta: feature, package: bot, package: locales

#103 refactor: improve locale types
  packages/bot/package.json
  packages/bot/src/commands/Configuration/_config_suggestions.ts
  packages/bot/src/commands/Information/_server_banner.ts
  packages/bot/src/commands/Information/_server_info.ts
  packages/bot/src/commands/Utils/suggestion.ts
  packages/bot/src/events/interactionCreate.ts
  packages/bot/src/events/messageCreate.ts
  packages/bot/src/lib/managers/LanguageManager.ts
  packages/bot/src/structures/Command.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  yarn.lock
Labels: meta: refactor, package: bot, package: locales

#104 chore: add readme to packages
  README.md
  packages/bot/README.md
  packages/locales/README.md
  packages/logger/README.md
  packages/prisma/README.md
  packages/webserver/README.md
Labels: type: consistency

#113 feat: add autocomplete handler on commands
  packages/bot/src/events/interactionCreate.ts
  packages/bot/src/structures/Command.ts
Labels: meta: feature, package: bot

#108 feat: giveaway command
  packages/bot/package.json
  packages/bot/src/commands/Moderation/ban.ts
  packages/bot/src/commands/Moderation/data/giveaway.ts
  packages/bot/src/commands/Moderation/giveaway.ts
  packages/bot/src/events/interactionCreate.ts
  packages/bot/src/helpers/Giveaway.ts
  packages/bot/src/helpers/Timestamp.ts
  packages/bot/src/lib/managers/DatabaseManager.ts
  packages/bot/src/lib/tasks/giveaway.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/locales/assets/commandDescriptions/en_US/index.ts
  packages/locales/assets/commandDescriptions/pt_BR/index.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
  packages/prisma/providers/cockroachdb/schema.prisma
  packages/prisma/providers/mongodb/schema.prisma
  packages/prisma/providers/postgresql/migrations/20220714103110_giveaways/migration.sql
  packages/prisma/providers/postgresql/schema.prisma
  yarn.lock
Labels: meta: feature, meta: dependencies, package: bot, package: locales, meta: database, meta: tasks, meta: localization

#118 feat(bot): lockdown command
  packages/bot/src/commands/Moderation/data/lockdown.ts
  packages/bot/src/commands/Moderation/lockdown.ts
  packages/bot/src/lib/managers/DatabaseManager.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/locales/assets/commandDescriptions/en_US/index.ts
  packages/locales/assets/commandDescriptions/pt_BR/index.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
  packages/prisma/providers/cockroachdb/migrations/20220717211030_lockdown/migration.sql
  packages/prisma/providers/cockroachdb/schema.prisma
  packages/prisma/providers/mongodb/schema.prisma
  packages/prisma/providers/postgresql/migrations/20220717211016_lockdown/migration.sql
  packages/prisma/providers/postgresql/schema.prisma
Labels: meta: feature, package: bot, package: locales, meta: database, meta: localization

#126 chore: remove turborepo
  .github/workflows/test.yml
  .gitignore
  .yarn/releases/yarn-4.0.0-rc.13.cjs
  .yarnrc
  .yarnrc.yml
  package.json
  packages/bot/package.json
  packages/locales/package.json
  packages/logger/package.json
  packages/prisma/package.json
  packages/webserver/package.json
  turbo.json
  yarn.lock
Labels: meta: dependencies, meta: github

#129 refactor: cleanup, fix CI
  .github/workflows/test.yml
  .yarnrc.yml
  package.json
  packages/bot/.env.example
  packages/bot/.eslintrc.json
  packages/bot/config.example.json
  packages/bot/package.json
  packages/bot/src/lib/managers/DatabaseManager.ts
  packages/bot/src/lib/modules/Database.ts
  packages/locales/package.json
  packages/logger/package.json
  packages/prisma/package.json
  packages/webserver/package.json
  yarn.lock
Labels: meta: dependencies, package: bot, meta: database, meta: github

#130 Added a bot emoji in the title
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
Labels: package: locales, meta: localization

#134 feat(bot): reminders
  packages/bot/package.json
  packages/bot/src/commands/Utils/data/remind.ts
  packages/bot/src/commands/Utils/remind.ts
  packages/bot/src/helpers/IdGenerator.ts
  packages/bot/src/helpers/Reminder.ts
  packages/bot/src/lib/managers/DatabaseManager.ts
  packages/bot/src/lib/tasks/reminder.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/locales/assets/commandDescriptions/en_US/index.ts
  packages/locales/assets/commandDescriptions/pt_BR/index.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
  packages/prisma/providers/cockroachdb/migrations/20220720134739_reminders/migration.sql
  packages/prisma/providers/cockroachdb/schema.prisma
  packages/prisma/providers/mongodb/schema.prisma
  packages/prisma/providers/postgresql/migrations/20220720134701_reminders/migration.sql
  packages/prisma/providers/postgresql/schema.prisma
  yarn.lock
Labels: meta: dependencies, package: bot, package: locales, meta: database, meta: tasks, meta: localization

#110 feat(bot): add /ban info, ban list and unban command
  packages/bot/src/commands/Information/_server_banner.ts
  packages/bot/src/commands/Information/_server_icon.ts
  packages/bot/src/commands/Information/_server_info.ts
  packages/bot/src/commands/Moderation/_ban_info.ts
  packages/bot/src/commands/Moderation/_ban_list.ts
  packages/bot/src/commands/Moderation/_ban_remove.ts
  packages/bot/src/commands/Moderation/_ban_user.ts
  packages/bot/src/commands/Moderation/ban.ts
  packages/bot/src/commands/Moderation/data/ban.ts
  packages/locales/assets/command/en_US/index.ts
  packages/locales/assets/command/pt_BR/index.ts
  packages/locales/assets/commandDescriptions/en_US/index.ts
  packages/locales/assets/commandDescriptions/pt_BR/index.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
Labels: meta: feature, status: WIP, package: bot, package: locales, meta: localization

#139 refactor: simplify command data
  packages/bot/src/commands/Configuration/data/config.ts
  packages/bot/src/commands/Information/data/bot.ts
  packages/bot/src/commands/Information/data/server.ts
  packages/bot/src/commands/Information/data/user.ts
  packages/bot/src/commands/Moderation/data/ban.ts
  packages/bot/src/commands/Moderation/data/giveaway.ts
  packages/bot/src/commands/Moderation/data/kick.ts
  packages/bot/src/commands/Moderation/data/lockdown.ts
  packages/bot/src/commands/Moderation/data/mute.ts
  packages/bot/src/commands/Moderation/data/poll.ts
  packages/bot/src/commands/Text/data/text.ts
  packages/bot/src/commands/Utils/data/afk.ts
  packages/bot/src/commands/Utils/data/animal.ts
  packages/bot/src/commands/Utils/data/help.ts
  packages/bot/src/commands/Utils/data/ping.ts
  packages/bot/src/commands/Utils/data/suggestion.ts
  packages/bot/src/commands/Utils/data/wikipedia.ts
  packages/bot/src/structures/CommandDataStructure.ts
  packages/locales/assets/commandNames/en_US/index.ts
  packages/locales/assets/commandNames/pt_BR/index.ts
Labels: package: bot, package: locales, meta: localization
